#!/bin/sh

set -e

all_my_little_repos() {
	ls -d */*/.git \
		| sed -e 's|/\.git$||'
}

count_branches() {
	(
		cd $1
		echo $(git branch | wc -l)
	)
}

show_if_more_than_one_branch() {
	[ 1 -eq $(count_branches $1) ] || echo $1
}

main() {
	cd ~/trees/pkgsrc-cvs
	for i in $(all_my_little_repos); do
		show_if_more_than_one_branch "$i"
	done
}

main "$@"
exit $?
